### ISSUE TITLE
Implement the `save` function

### ISSUE THREAD

**Issue by rkbryant** [soegaard/sketching#23]
Implement the `save` function. Allow users to append a file extension to the name of the file which indicates the file format to be used. (`.png` `.tif`  `.jpg` and `.tga`?)

**Comment by soegaard** [comment]
Hi @rkbryant 

I have implemented `save` and pushed the new version to Github.

The supported file formats are: png, gif, bmp and jpeg.

The documentation is here:
https://soegaard.github.io/sketching/Reference.html#%28part._save%29

In order to update your copy of Sketching, you can use the package manager inside DrRacket
(see the "File" menu). Alternatively, you can use 

    raco pkg update sketching

in the terminal.

Thanks for the suggestion.
