### ISSUE TITLE
Vector access documentation 

### ISSUE THREAD

**Issue by hasn0life** [soegaard/sketching#34]
It seems that you've implemented a notation for accessing vectors like v_1 that isn't documented anywhere except the [assignment](https://soegaard.github.io/sketching/Reference.html#%28part.__~3d__.Assignment_%29) operator section. I would think it would be better served in its own section, or at least referenced in the overview like the dot notation is (and dot notation should possibly have its own section? Dot notation documentation makes sense in class and struct because that's where it's used, but there's no vector section to introduce vector access notation)

Also can you possibly introduce some kind of sugar for vector length to go with the vector access notation? Maybe like v_len or v_length?

**Comment by soegaard** [comment]
The _ notation was an experiment, so I left it out of the documentation.

I have since implemented something better, namely indexing using square brackets as in:  v[1] 
That hasn't been commited yet - I need to test thouroughly first.
I expect to get some time during christmas to do it properly.

Wrt to sugar to get the length of a vector: I belive v.length works.
Just note that `(vector-length v)` is faster, since `v.length` has to figure out that v is a vector first, 
and then call vector-length afterwards.

**Comment by hasn0life** [comment]
That sounds awesome, I'm looking forward to it!

**Comment by soegaard** [comment]
@hasn0life 

This has now been added.  You can now write  `id[expr]` instead of `(vector-ref id expr)`, `(string-ref id expr)` and `(list-ref id expr)`.
