### ISSUE TITLE
Error building documentation

### ISSUE THREAD

**Issue by samdphillips** [soegaard/sketching#48]
Racket 8.3.0.8

```
raco setup: running: <pkgs>/sketching-doc/sketching-doc/manual-sketching.scrbl
examples: exception raised in example
  error: "cairo_matrix_init: arity mismatch;\n the expected number of arguments does not match the given number\n  expected: 7\n  given: 6"
  context...:
   /Applications/Racket v8.3.0.8/collects/racket/private/more-scheme.rkt:163:2: select-handler/no-breaks
   /Applications/Racket v8.3.0.8/share/pkgs/scribble-lib/scribble/eval.rkt:356:9
   .../private/map.rkt:40:19: loop
   [repeats 3 more times]
   body of "/Users/sphillips/Library/Racket/snapshot/pkgs/sketching-doc/sketching-doc/manual-sketching.scrbl"
```

**Comment by soegaard** [comment]
Hi,

Thanks for letting me know. I use Github Actions to build the documention and for each
pull request it automatically builds the documentation and pushes the new documentation 
to soegaard.github.io/sketching.

I just checked and I see it builds with no problem on Racket 8.1.

![image](https://user-images.githubusercontent.com/461765/149172932-885bb3bf-aa53-4e38-a79b-2c958cc36a93.png)

Something must have changed with 8.3.
But cairo_matrix_init isn't called directly by Sketching, so maybe there is a change in racket/draw?

/Jens Axel

**Comment by soegaard** [comment]
Maybe it is related to this fix I made to `cairo` in November?

![image](https://user-images.githubusercontent.com/461765/149175879-0f600be0-2165-4f0d-b11f-45f5858c496f.png)

Can you check what   `cairo-lib/cairo/main.rkt` contains on your machine?

If that's not the problem:

Does `#lang sketching` programs work at all, when you run them in, say, DrRacket?
That is, is this a documentation only problem?

What platform are you on?



-- Here are some pieces to the puzzle --

The function `cairo_matrix_init` is defined here and require 7 arguments:
https://github.com/racket/draw/blob/0df41bbada3d9061b83f394f01590c34c127d0cf/draw-lib/racket/draw/unsafe/cairo.rkt#L204

The Cairo docs says the function is has been that way since Cairo 1.0 so it must be some piece of code calling it.
The effect of `cairo_matrix_init` is to set the initial affine transformation.
If the problem is not a version issue with `cairo-lib` I am not sure whether I need to look in
 Sketching, racket/gui or racket/draw.
The function `cairo_matrix_init` isn't called directly by Sketching.

**Comment by samdphillips** [comment]
> Can you check what cairo-lib/cairo/main.rkt contains on your machine?

Yes, it appears to be the version on the right.

> Does #lang sketching programs work at all, when you run them in, say, DrRacket?
> That is, is this a documentation only problem?

A simple sketching program like this works:
```
#lang sketching

(define (draw) (line 0 0 100 100))
```

> What platform are you on?

MacOS Catalina x86

I will try the easiest thing first and upgrade the `cairo-lib` package.

**Comment by samdphillips** [comment]
Upgrading `cairo-lib` to the latest fixed it.   The docs now build for me.

**Comment by soegaard** [comment]
Great to hear!

**Comment by soegaard** [comment]
Hmm. Does the error mean I missing to state a dependency somewhere?

**Comment by samdphillips** [comment]
Perhaps if you had a version dependency on `cairo-lib`?  You may need to bump the version number, though.

**Comment by soegaard** [comment]
Thanks for the tip. I bumped the version of `cairo` to 1.1.
